version: "3.8"

services:
  traefik:
    image: traefik:v3.4

    networks:
      - labs_proxy

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs:ro
      - ./traefik/dynamic:/dynamic:ro
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro

    deploy:
      mode: replicated
      replicas: 1
      placement:

        constraints:
          - node.role == manager

      labels:
        - "traefik.enable=true"

  whoami:
    image: traefik/whoami
    networks:
      - labs_proxy
    deploy:
      labels:
        - "traefik.enable=true"

networks:
  labs_proxy:
    driver: overlay
    attachable: true
