# Static configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: true

providers:
  file:
    directory: "/dynamic"
    watch: true
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: labs_proxy

api:
  dashboard: true
  insecure: false

log:
  level: "INFO"

accessLog: {}

metrics:
  prometheus: {}